// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/kolobublik/limit-order-book/internal/biz"
	"github.com/kolobublik/limit-order-book/internal/conf"
	"github.com/kolobublik/limit-order-book/internal/data"
	"github.com/kolobublik/limit-order-book/internal/server"
	"github.com/kolobublik/limit-order-book/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	orderBookRepo := data.NewOrderBookRepo(dataData, logger)
	orderBookUsecase := biz.NewOrderBookUsecase(orderBookRepo, logger)
	orderBookService := service.NewOrderBookService(orderBookUsecase, logger)
	client, err := data.NewFIXClient(confData, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	fixService := service.NewFIXService(client)
	grpcServer := server.NewGRPCServer(confServer, orderBookService, fixService, logger)
	httpServer := server.NewHTTPServer(confServer, fixService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
