// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: fix/v1/fix.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// OrderType represents the type of order
type OrderType int32

const (
	OrderType_ORDER_TYPE_UNSPECIFIED OrderType = 0
	OrderType_ORDER_TYPE_MARKET      OrderType = 1
	OrderType_ORDER_TYPE_LIMIT       OrderType = 2
	OrderType_ORDER_TYPE_VWAP        OrderType = 3
)

// Enum value maps for OrderType.
var (
	OrderType_name = map[int32]string{
		0: "ORDER_TYPE_UNSPECIFIED",
		1: "ORDER_TYPE_MARKET",
		2: "ORDER_TYPE_LIMIT",
		3: "ORDER_TYPE_VWAP",
	}
	OrderType_value = map[string]int32{
		"ORDER_TYPE_UNSPECIFIED": 0,
		"ORDER_TYPE_MARKET":      1,
		"ORDER_TYPE_LIMIT":       2,
		"ORDER_TYPE_VWAP":        3,
	}
)

func (x OrderType) Enum() *OrderType {
	p := new(OrderType)
	*p = x
	return p
}

func (x OrderType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderType) Descriptor() protoreflect.EnumDescriptor {
	return file_fix_v1_fix_proto_enumTypes[0].Descriptor()
}

func (OrderType) Type() protoreflect.EnumType {
	return &file_fix_v1_fix_proto_enumTypes[0]
}

func (x OrderType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderType.Descriptor instead.
func (OrderType) EnumDescriptor() ([]byte, []int) {
	return file_fix_v1_fix_proto_rawDescGZIP(), []int{0}
}

// Side represents the side of the order (buy/sell)
type Side int32

const (
	Side_SIDE_UNSPECIFIED Side = 0
	Side_SIDE_BUY         Side = 1
	Side_SIDE_SELL        Side = 2
)

// Enum value maps for Side.
var (
	Side_name = map[int32]string{
		0: "SIDE_UNSPECIFIED",
		1: "SIDE_BUY",
		2: "SIDE_SELL",
	}
	Side_value = map[string]int32{
		"SIDE_UNSPECIFIED": 0,
		"SIDE_BUY":         1,
		"SIDE_SELL":        2,
	}
)

func (x Side) Enum() *Side {
	p := new(Side)
	*p = x
	return p
}

func (x Side) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Side) Descriptor() protoreflect.EnumDescriptor {
	return file_fix_v1_fix_proto_enumTypes[1].Descriptor()
}

func (Side) Type() protoreflect.EnumType {
	return &file_fix_v1_fix_proto_enumTypes[1]
}

func (x Side) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Side.Descriptor instead.
func (Side) EnumDescriptor() ([]byte, []int) {
	return file_fix_v1_fix_proto_rawDescGZIP(), []int{1}
}

// QuantityType represents how the quantity is specified (base/quote)
type QuantityType int32

const (
	QuantityType_QUANTITY_TYPE_UNSPECIFIED QuantityType = 0
	QuantityType_QUANTITY_TYPE_BASE        QuantityType = 1
	QuantityType_QUANTITY_TYPE_QUOTE       QuantityType = 2
)

// Enum value maps for QuantityType.
var (
	QuantityType_name = map[int32]string{
		0: "QUANTITY_TYPE_UNSPECIFIED",
		1: "QUANTITY_TYPE_BASE",
		2: "QUANTITY_TYPE_QUOTE",
	}
	QuantityType_value = map[string]int32{
		"QUANTITY_TYPE_UNSPECIFIED": 0,
		"QUANTITY_TYPE_BASE":        1,
		"QUANTITY_TYPE_QUOTE":       2,
	}
)

func (x QuantityType) Enum() *QuantityType {
	p := new(QuantityType)
	*p = x
	return p
}

func (x QuantityType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QuantityType) Descriptor() protoreflect.EnumDescriptor {
	return file_fix_v1_fix_proto_enumTypes[2].Descriptor()
}

func (QuantityType) Type() protoreflect.EnumType {
	return &file_fix_v1_fix_proto_enumTypes[2]
}

func (x QuantityType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QuantityType.Descriptor instead.
func (QuantityType) EnumDescriptor() ([]byte, []int) {
	return file_fix_v1_fix_proto_rawDescGZIP(), []int{2}
}

// Order represents a new order request
type Order struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Symbol       string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	OrderType    OrderType              `protobuf:"varint,2,opt,name=order_type,json=orderType,proto3,enum=api.fix.v1.OrderType" json:"order_type,omitempty"`
	Side         Side                   `protobuf:"varint,3,opt,name=side,proto3,enum=api.fix.v1.Side" json:"side,omitempty"`
	QuantityType QuantityType           `protobuf:"varint,4,opt,name=quantity_type,json=quantityType,proto3,enum=api.fix.v1.QuantityType" json:"quantity_type,omitempty"`
	Quantity     string                 `protobuf:"bytes,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price        string                 `protobuf:"bytes,6,opt,name=price,proto3" json:"price,omitempty"`
	// Optional fields for VWAP orders
	StartTime         string `protobuf:"bytes,7,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	ParticipationRate string `protobuf:"bytes,8,opt,name=participation_rate,json=participationRate,proto3" json:"participation_rate,omitempty"`
	ExpireTime        string `protobuf:"bytes,9,opt,name=expire_time,json=expireTime,proto3" json:"expire_time,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_fix_v1_fix_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_fix_v1_fix_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_fix_v1_fix_proto_rawDescGZIP(), []int{0}
}

func (x *Order) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Order) GetOrderType() OrderType {
	if x != nil {
		return x.OrderType
	}
	return OrderType_ORDER_TYPE_UNSPECIFIED
}

func (x *Order) GetSide() Side {
	if x != nil {
		return x.Side
	}
	return Side_SIDE_UNSPECIFIED
}

func (x *Order) GetQuantityType() QuantityType {
	if x != nil {
		return x.QuantityType
	}
	return QuantityType_QUANTITY_TYPE_UNSPECIFIED
}

func (x *Order) GetQuantity() string {
	if x != nil {
		return x.Quantity
	}
	return ""
}

func (x *Order) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *Order) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *Order) GetParticipationRate() string {
	if x != nil {
		return x.ParticipationRate
	}
	return ""
}

func (x *Order) GetExpireTime() string {
	if x != nil {
		return x.ExpireTime
	}
	return ""
}

// OrderInfo represents order information for status and cancellation
type OrderInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClOrdId       string                 `protobuf:"bytes,1,opt,name=cl_ord_id,json=clOrdId,proto3" json:"cl_ord_id,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Symbol        string                 `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Side          string                 `protobuf:"bytes,4,opt,name=side,proto3" json:"side,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Type          string                 `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`
	Price         string                 `protobuf:"bytes,7,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      string                 `protobuf:"bytes,8,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderInfo) Reset() {
	*x = OrderInfo{}
	mi := &file_fix_v1_fix_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderInfo) ProtoMessage() {}

func (x *OrderInfo) ProtoReflect() protoreflect.Message {
	mi := &file_fix_v1_fix_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderInfo.ProtoReflect.Descriptor instead.
func (*OrderInfo) Descriptor() ([]byte, []int) {
	return file_fix_v1_fix_proto_rawDescGZIP(), []int{1}
}

func (x *OrderInfo) GetClOrdId() string {
	if x != nil {
		return x.ClOrdId
	}
	return ""
}

func (x *OrderInfo) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *OrderInfo) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *OrderInfo) GetSide() string {
	if x != nil {
		return x.Side
	}
	return ""
}

func (x *OrderInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *OrderInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *OrderInfo) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *OrderInfo) GetQuantity() string {
	if x != nil {
		return x.Quantity
	}
	return ""
}

// PlaceOrderRequest represents a request to place a new order
type PlaceOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaceOrderRequest) Reset() {
	*x = PlaceOrderRequest{}
	mi := &file_fix_v1_fix_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceOrderRequest) ProtoMessage() {}

func (x *PlaceOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fix_v1_fix_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceOrderRequest.ProtoReflect.Descriptor instead.
func (*PlaceOrderRequest) Descriptor() ([]byte, []int) {
	return file_fix_v1_fix_proto_rawDescGZIP(), []int{2}
}

func (x *PlaceOrderRequest) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

// PlaceOrderResponse represents the response from placing an order
type PlaceOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClOrdId       string                 `protobuf:"bytes,1,opt,name=cl_ord_id,json=clOrdId,proto3" json:"cl_ord_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaceOrderResponse) Reset() {
	*x = PlaceOrderResponse{}
	mi := &file_fix_v1_fix_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceOrderResponse) ProtoMessage() {}

func (x *PlaceOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fix_v1_fix_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceOrderResponse.ProtoReflect.Descriptor instead.
func (*PlaceOrderResponse) Descriptor() ([]byte, []int) {
	return file_fix_v1_fix_proto_rawDescGZIP(), []int{3}
}

func (x *PlaceOrderResponse) GetClOrdId() string {
	if x != nil {
		return x.ClOrdId
	}
	return ""
}

func (x *PlaceOrderResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// GetOrderStatusRequest represents a request to get order status
type GetOrderStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderInfo     *OrderInfo             `protobuf:"bytes,1,opt,name=order_info,json=orderInfo,proto3" json:"order_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderStatusRequest) Reset() {
	*x = GetOrderStatusRequest{}
	mi := &file_fix_v1_fix_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderStatusRequest) ProtoMessage() {}

func (x *GetOrderStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fix_v1_fix_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderStatusRequest.ProtoReflect.Descriptor instead.
func (*GetOrderStatusRequest) Descriptor() ([]byte, []int) {
	return file_fix_v1_fix_proto_rawDescGZIP(), []int{4}
}

func (x *GetOrderStatusRequest) GetOrderInfo() *OrderInfo {
	if x != nil {
		return x.OrderInfo
	}
	return nil
}

// GetOrderStatusResponse represents the response with order status
type GetOrderStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderInfo     *OrderInfo             `protobuf:"bytes,1,opt,name=order_info,json=orderInfo,proto3" json:"order_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderStatusResponse) Reset() {
	*x = GetOrderStatusResponse{}
	mi := &file_fix_v1_fix_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderStatusResponse) ProtoMessage() {}

func (x *GetOrderStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fix_v1_fix_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderStatusResponse.ProtoReflect.Descriptor instead.
func (*GetOrderStatusResponse) Descriptor() ([]byte, []int) {
	return file_fix_v1_fix_proto_rawDescGZIP(), []int{5}
}

func (x *GetOrderStatusResponse) GetOrderInfo() *OrderInfo {
	if x != nil {
		return x.OrderInfo
	}
	return nil
}

// CancelOrderRequest represents a request to cancel an order
type CancelOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderInfo     *OrderInfo             `protobuf:"bytes,1,opt,name=order_info,json=orderInfo,proto3" json:"order_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderRequest) Reset() {
	*x = CancelOrderRequest{}
	mi := &file_fix_v1_fix_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderRequest) ProtoMessage() {}

func (x *CancelOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fix_v1_fix_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderRequest.ProtoReflect.Descriptor instead.
func (*CancelOrderRequest) Descriptor() ([]byte, []int) {
	return file_fix_v1_fix_proto_rawDescGZIP(), []int{6}
}

func (x *CancelOrderRequest) GetOrderInfo() *OrderInfo {
	if x != nil {
		return x.OrderInfo
	}
	return nil
}

// CancelOrderResponse represents the response from cancelling an order
type CancelOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderResponse) Reset() {
	*x = CancelOrderResponse{}
	mi := &file_fix_v1_fix_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderResponse) ProtoMessage() {}

func (x *CancelOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fix_v1_fix_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderResponse.ProtoReflect.Descriptor instead.
func (*CancelOrderResponse) Descriptor() ([]byte, []int) {
	return file_fix_v1_fix_proto_rawDescGZIP(), []int{7}
}

func (x *CancelOrderResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_fix_v1_fix_proto protoreflect.FileDescriptor

const file_fix_v1_fix_proto_rawDesc = "" +
	"\n" +
	"\x10fix/v1/fix.proto\x12\n" +
	"api.fix.v1\"\xdb\x02\n" +
	"\x05Order\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x124\n" +
	"\n" +
	"order_type\x18\x02 \x01(\x0e2\x15.api.fix.v1.OrderTypeR\torderType\x12$\n" +
	"\x04side\x18\x03 \x01(\x0e2\x10.api.fix.v1.SideR\x04side\x12=\n" +
	"\rquantity_type\x18\x04 \x01(\x0e2\x18.api.fix.v1.QuantityTypeR\fquantityType\x12\x1a\n" +
	"\bquantity\x18\x05 \x01(\tR\bquantity\x12\x14\n" +
	"\x05price\x18\x06 \x01(\tR\x05price\x12\x1d\n" +
	"\n" +
	"start_time\x18\a \x01(\tR\tstartTime\x12-\n" +
	"\x12participation_rate\x18\b \x01(\tR\x11participationRate\x12\x1f\n" +
	"\vexpire_time\x18\t \x01(\tR\n" +
	"expireTime\"\xcc\x01\n" +
	"\tOrderInfo\x12\x1a\n" +
	"\tcl_ord_id\x18\x01 \x01(\tR\aclOrdId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\x16\n" +
	"\x06symbol\x18\x03 \x01(\tR\x06symbol\x12\x12\n" +
	"\x04side\x18\x04 \x01(\tR\x04side\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x12\n" +
	"\x04type\x18\x06 \x01(\tR\x04type\x12\x14\n" +
	"\x05price\x18\a \x01(\tR\x05price\x12\x1a\n" +
	"\bquantity\x18\b \x01(\tR\bquantity\"<\n" +
	"\x11PlaceOrderRequest\x12'\n" +
	"\x05order\x18\x01 \x01(\v2\x11.api.fix.v1.OrderR\x05order\"H\n" +
	"\x12PlaceOrderResponse\x12\x1a\n" +
	"\tcl_ord_id\x18\x01 \x01(\tR\aclOrdId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"M\n" +
	"\x15GetOrderStatusRequest\x124\n" +
	"\n" +
	"order_info\x18\x01 \x01(\v2\x15.api.fix.v1.OrderInfoR\torderInfo\"N\n" +
	"\x16GetOrderStatusResponse\x124\n" +
	"\n" +
	"order_info\x18\x01 \x01(\v2\x15.api.fix.v1.OrderInfoR\torderInfo\"J\n" +
	"\x12CancelOrderRequest\x124\n" +
	"\n" +
	"order_info\x18\x01 \x01(\v2\x15.api.fix.v1.OrderInfoR\torderInfo\"-\n" +
	"\x13CancelOrderResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status*i\n" +
	"\tOrderType\x12\x1a\n" +
	"\x16ORDER_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11ORDER_TYPE_MARKET\x10\x01\x12\x14\n" +
	"\x10ORDER_TYPE_LIMIT\x10\x02\x12\x13\n" +
	"\x0fORDER_TYPE_VWAP\x10\x03*9\n" +
	"\x04Side\x12\x14\n" +
	"\x10SIDE_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bSIDE_BUY\x10\x01\x12\r\n" +
	"\tSIDE_SELL\x10\x02*^\n" +
	"\fQuantityType\x12\x1d\n" +
	"\x19QUANTITY_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12QUANTITY_TYPE_BASE\x10\x01\x12\x17\n" +
	"\x13QUANTITY_TYPE_QUOTE\x10\x022\x88\x02\n" +
	"\n" +
	"FIXService\x12M\n" +
	"\n" +
	"PlaceOrder\x12\x1d.api.fix.v1.PlaceOrderRequest\x1a\x1e.api.fix.v1.PlaceOrderResponse\"\x00\x12Y\n" +
	"\x0eGetOrderStatus\x12!.api.fix.v1.GetOrderStatusRequest\x1a\".api.fix.v1.GetOrderStatusResponse\"\x00\x12P\n" +
	"\vCancelOrder\x12\x1e.api.fix.v1.CancelOrderRequest\x1a\x1f.api.fix.v1.CancelOrderResponse\"\x00B6Z4github.com/kolobublik/limit-order-book/api/fix/v1;v1b\x06proto3"

var (
	file_fix_v1_fix_proto_rawDescOnce sync.Once
	file_fix_v1_fix_proto_rawDescData []byte
)

func file_fix_v1_fix_proto_rawDescGZIP() []byte {
	file_fix_v1_fix_proto_rawDescOnce.Do(func() {
		file_fix_v1_fix_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fix_v1_fix_proto_rawDesc), len(file_fix_v1_fix_proto_rawDesc)))
	})
	return file_fix_v1_fix_proto_rawDescData
}

var file_fix_v1_fix_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_fix_v1_fix_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_fix_v1_fix_proto_goTypes = []any{
	(OrderType)(0),                 // 0: api.fix.v1.OrderType
	(Side)(0),                      // 1: api.fix.v1.Side
	(QuantityType)(0),              // 2: api.fix.v1.QuantityType
	(*Order)(nil),                  // 3: api.fix.v1.Order
	(*OrderInfo)(nil),              // 4: api.fix.v1.OrderInfo
	(*PlaceOrderRequest)(nil),      // 5: api.fix.v1.PlaceOrderRequest
	(*PlaceOrderResponse)(nil),     // 6: api.fix.v1.PlaceOrderResponse
	(*GetOrderStatusRequest)(nil),  // 7: api.fix.v1.GetOrderStatusRequest
	(*GetOrderStatusResponse)(nil), // 8: api.fix.v1.GetOrderStatusResponse
	(*CancelOrderRequest)(nil),     // 9: api.fix.v1.CancelOrderRequest
	(*CancelOrderResponse)(nil),    // 10: api.fix.v1.CancelOrderResponse
}
var file_fix_v1_fix_proto_depIdxs = []int32{
	0,  // 0: api.fix.v1.Order.order_type:type_name -> api.fix.v1.OrderType
	1,  // 1: api.fix.v1.Order.side:type_name -> api.fix.v1.Side
	2,  // 2: api.fix.v1.Order.quantity_type:type_name -> api.fix.v1.QuantityType
	3,  // 3: api.fix.v1.PlaceOrderRequest.order:type_name -> api.fix.v1.Order
	4,  // 4: api.fix.v1.GetOrderStatusRequest.order_info:type_name -> api.fix.v1.OrderInfo
	4,  // 5: api.fix.v1.GetOrderStatusResponse.order_info:type_name -> api.fix.v1.OrderInfo
	4,  // 6: api.fix.v1.CancelOrderRequest.order_info:type_name -> api.fix.v1.OrderInfo
	5,  // 7: api.fix.v1.FIXService.PlaceOrder:input_type -> api.fix.v1.PlaceOrderRequest
	7,  // 8: api.fix.v1.FIXService.GetOrderStatus:input_type -> api.fix.v1.GetOrderStatusRequest
	9,  // 9: api.fix.v1.FIXService.CancelOrder:input_type -> api.fix.v1.CancelOrderRequest
	6,  // 10: api.fix.v1.FIXService.PlaceOrder:output_type -> api.fix.v1.PlaceOrderResponse
	8,  // 11: api.fix.v1.FIXService.GetOrderStatus:output_type -> api.fix.v1.GetOrderStatusResponse
	10, // 12: api.fix.v1.FIXService.CancelOrder:output_type -> api.fix.v1.CancelOrderResponse
	10, // [10:13] is the sub-list for method output_type
	7,  // [7:10] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_fix_v1_fix_proto_init() }
func file_fix_v1_fix_proto_init() {
	if File_fix_v1_fix_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fix_v1_fix_proto_rawDesc), len(file_fix_v1_fix_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fix_v1_fix_proto_goTypes,
		DependencyIndexes: file_fix_v1_fix_proto_depIdxs,
		EnumInfos:         file_fix_v1_fix_proto_enumTypes,
		MessageInfos:      file_fix_v1_fix_proto_msgTypes,
	}.Build()
	File_fix_v1_fix_proto = out.File
	file_fix_v1_fix_proto_goTypes = nil
	file_fix_v1_fix_proto_depIdxs = nil
}
