// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: orderbook/v1/orderbook.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Side int32

const (
	Side_SIDE_UNSPECIFIED Side = 0
	Side_BUY              Side = 1
	Side_SELL             Side = 2
)

// Enum value maps for Side.
var (
	Side_name = map[int32]string{
		0: "SIDE_UNSPECIFIED",
		1: "BUY",
		2: "SELL",
	}
	Side_value = map[string]int32{
		"SIDE_UNSPECIFIED": 0,
		"BUY":              1,
		"SELL":             2,
	}
)

func (x Side) Enum() *Side {
	p := new(Side)
	*p = x
	return p
}

func (x Side) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Side) Descriptor() protoreflect.EnumDescriptor {
	return file_orderbook_v1_orderbook_proto_enumTypes[0].Descriptor()
}

func (Side) Type() protoreflect.EnumType {
	return &file_orderbook_v1_orderbook_proto_enumTypes[0]
}

func (x Side) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Side.Descriptor instead.
func (Side) EnumDescriptor() ([]byte, []int) {
	return file_orderbook_v1_orderbook_proto_rawDescGZIP(), []int{0}
}

type OrderType int32

const (
	OrderType_ORDER_TYPE_UNSPECIFIED OrderType = 0
	OrderType_LIMIT                  OrderType = 1
	OrderType_MARKET                 OrderType = 2
	OrderType_STOP_LIMIT             OrderType = 3
	OrderType_STOP                   OrderType = 4
	OrderType_TAKE_PROFIT_STOP_LOSS  OrderType = 5
)

// Enum value maps for OrderType.
var (
	OrderType_name = map[int32]string{
		0: "ORDER_TYPE_UNSPECIFIED",
		1: "LIMIT",
		2: "MARKET",
		3: "STOP_LIMIT",
		4: "STOP",
		5: "TAKE_PROFIT_STOP_LOSS",
	}
	OrderType_value = map[string]int32{
		"ORDER_TYPE_UNSPECIFIED": 0,
		"LIMIT":                  1,
		"MARKET":                 2,
		"STOP_LIMIT":             3,
		"STOP":                   4,
		"TAKE_PROFIT_STOP_LOSS":  5,
	}
)

func (x OrderType) Enum() *OrderType {
	p := new(OrderType)
	*p = x
	return p
}

func (x OrderType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderType) Descriptor() protoreflect.EnumDescriptor {
	return file_orderbook_v1_orderbook_proto_enumTypes[1].Descriptor()
}

func (OrderType) Type() protoreflect.EnumType {
	return &file_orderbook_v1_orderbook_proto_enumTypes[1]
}

func (x OrderType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderType.Descriptor instead.
func (OrderType) EnumDescriptor() ([]byte, []int) {
	return file_orderbook_v1_orderbook_proto_rawDescGZIP(), []int{1}
}

type OrderStatus int32

const (
	OrderStatus_ORDER_STATUS_UNSPECIFIED OrderStatus = 0
	OrderStatus_WORKING                  OrderStatus = 1
	OrderStatus_DONE                     OrderStatus = 2
)

// Enum value maps for OrderStatus.
var (
	OrderStatus_name = map[int32]string{
		0: "ORDER_STATUS_UNSPECIFIED",
		1: "WORKING",
		2: "DONE",
	}
	OrderStatus_value = map[string]int32{
		"ORDER_STATUS_UNSPECIFIED": 0,
		"WORKING":                  1,
		"DONE":                     2,
	}
)

func (x OrderStatus) Enum() *OrderStatus {
	p := new(OrderStatus)
	*p = x
	return p
}

func (x OrderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_orderbook_v1_orderbook_proto_enumTypes[2].Descriptor()
}

func (OrderStatus) Type() protoreflect.EnumType {
	return &file_orderbook_v1_orderbook_proto_enumTypes[2]
}

func (x OrderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderStatus.Descriptor instead.
func (OrderStatus) EnumDescriptor() ([]byte, []int) {
	return file_orderbook_v1_orderbook_proto_rawDescGZIP(), []int{2}
}

type Order struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	ClientOrderId string                 `protobuf:"bytes,2,opt,name=client_order_id,json=clientOrderId,proto3" json:"client_order_id,omitempty"`
	Instrument    string                 `protobuf:"bytes,3,opt,name=instrument,proto3" json:"instrument,omitempty"`
	Side          Side                   `protobuf:"varint,4,opt,name=side,proto3,enum=orderbook.v1.Side" json:"side,omitempty"`
	Type          OrderType              `protobuf:"varint,5,opt,name=type,proto3,enum=orderbook.v1.OrderType" json:"type,omitempty"`
	Status        OrderStatus            `protobuf:"varint,6,opt,name=status,proto3,enum=orderbook.v1.OrderStatus" json:"status,omitempty"`
	Price         float64                `protobuf:"fixed64,7,opt,name=price,proto3" json:"price,omitempty"`
	Size          float64                `protobuf:"fixed64,8,opt,name=size,proto3" json:"size,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_orderbook_v1_orderbook_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_orderbook_v1_orderbook_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_orderbook_v1_orderbook_proto_rawDescGZIP(), []int{0}
}

func (x *Order) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *Order) GetClientOrderId() string {
	if x != nil {
		return x.ClientOrderId
	}
	return ""
}

func (x *Order) GetInstrument() string {
	if x != nil {
		return x.Instrument
	}
	return ""
}

func (x *Order) GetSide() Side {
	if x != nil {
		return x.Side
	}
	return Side_SIDE_UNSPECIFIED
}

func (x *Order) GetType() OrderType {
	if x != nil {
		return x.Type
	}
	return OrderType_ORDER_TYPE_UNSPECIFIED
}

func (x *Order) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_ORDER_STATUS_UNSPECIFIED
}

func (x *Order) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Order) GetSize() float64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Order) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CreateOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientOrderId string                 `protobuf:"bytes,1,opt,name=client_order_id,json=clientOrderId,proto3" json:"client_order_id,omitempty"`
	Instrument    string                 `protobuf:"bytes,2,opt,name=instrument,proto3" json:"instrument,omitempty"`
	Side          Side                   `protobuf:"varint,3,opt,name=side,proto3,enum=orderbook.v1.Side" json:"side,omitempty"`
	Type          OrderType              `protobuf:"varint,4,opt,name=type,proto3,enum=orderbook.v1.OrderType" json:"type,omitempty"`
	Price         float64                `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	Size          float64                `protobuf:"fixed64,6,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_orderbook_v1_orderbook_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orderbook_v1_orderbook_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_orderbook_v1_orderbook_proto_rawDescGZIP(), []int{1}
}

func (x *CreateOrderRequest) GetClientOrderId() string {
	if x != nil {
		return x.ClientOrderId
	}
	return ""
}

func (x *CreateOrderRequest) GetInstrument() string {
	if x != nil {
		return x.Instrument
	}
	return ""
}

func (x *CreateOrderRequest) GetSide() Side {
	if x != nil {
		return x.Side
	}
	return Side_SIDE_UNSPECIFIED
}

func (x *CreateOrderRequest) GetType() OrderType {
	if x != nil {
		return x.Type
	}
	return OrderType_ORDER_TYPE_UNSPECIFIED
}

func (x *CreateOrderRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateOrderRequest) GetSize() float64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type GetOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderRequest) Reset() {
	*x = GetOrderRequest{}
	mi := &file_orderbook_v1_orderbook_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderRequest) ProtoMessage() {}

func (x *GetOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orderbook_v1_orderbook_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderRequest.ProtoReflect.Descriptor instead.
func (*GetOrderRequest) Descriptor() ([]byte, []int) {
	return file_orderbook_v1_orderbook_proto_rawDescGZIP(), []int{2}
}

func (x *GetOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type CancelOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderRequest) Reset() {
	*x = CancelOrderRequest{}
	mi := &file_orderbook_v1_orderbook_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderRequest) ProtoMessage() {}

func (x *CancelOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orderbook_v1_orderbook_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderRequest.ProtoReflect.Descriptor instead.
func (*CancelOrderRequest) Descriptor() ([]byte, []int) {
	return file_orderbook_v1_orderbook_proto_rawDescGZIP(), []int{3}
}

func (x *CancelOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type CancelOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Status        OrderStatus            `protobuf:"varint,2,opt,name=status,proto3,enum=orderbook.v1.OrderStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderResponse) Reset() {
	*x = CancelOrderResponse{}
	mi := &file_orderbook_v1_orderbook_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderResponse) ProtoMessage() {}

func (x *CancelOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orderbook_v1_orderbook_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderResponse.ProtoReflect.Descriptor instead.
func (*CancelOrderResponse) Descriptor() ([]byte, []int) {
	return file_orderbook_v1_orderbook_proto_rawDescGZIP(), []int{4}
}

func (x *CancelOrderResponse) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CancelOrderResponse) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_ORDER_STATUS_UNSPECIFIED
}

type ListOrdersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instrument    string                 `protobuf:"bytes,1,opt,name=instrument,proto3" json:"instrument,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersRequest) Reset() {
	*x = ListOrdersRequest{}
	mi := &file_orderbook_v1_orderbook_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersRequest) ProtoMessage() {}

func (x *ListOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orderbook_v1_orderbook_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersRequest.ProtoReflect.Descriptor instead.
func (*ListOrdersRequest) Descriptor() ([]byte, []int) {
	return file_orderbook_v1_orderbook_proto_rawDescGZIP(), []int{5}
}

func (x *ListOrdersRequest) GetInstrument() string {
	if x != nil {
		return x.Instrument
	}
	return ""
}

type ListOrdersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*Order               `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersResponse) Reset() {
	*x = ListOrdersResponse{}
	mi := &file_orderbook_v1_orderbook_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersResponse) ProtoMessage() {}

func (x *ListOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orderbook_v1_orderbook_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersResponse.ProtoReflect.Descriptor instead.
func (*ListOrdersResponse) Descriptor() ([]byte, []int) {
	return file_orderbook_v1_orderbook_proto_rawDescGZIP(), []int{6}
}

func (x *ListOrdersResponse) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

type InstrumentQuote struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instrument    string                 `protobuf:"bytes,1,opt,name=instrument,proto3" json:"instrument,omitempty"`
	BestBidPrice  float64                `protobuf:"fixed64,2,opt,name=best_bid_price,json=bestBidPrice,proto3" json:"best_bid_price,omitempty"`
	BestBidSize   float64                `protobuf:"fixed64,3,opt,name=best_bid_size,json=bestBidSize,proto3" json:"best_bid_size,omitempty"`
	BestAskPrice  float64                `protobuf:"fixed64,4,opt,name=best_ask_price,json=bestAskPrice,proto3" json:"best_ask_price,omitempty"`
	BestAskSize   float64                `protobuf:"fixed64,5,opt,name=best_ask_size,json=bestAskSize,proto3" json:"best_ask_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstrumentQuote) Reset() {
	*x = InstrumentQuote{}
	mi := &file_orderbook_v1_orderbook_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstrumentQuote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstrumentQuote) ProtoMessage() {}

func (x *InstrumentQuote) ProtoReflect() protoreflect.Message {
	mi := &file_orderbook_v1_orderbook_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstrumentQuote.ProtoReflect.Descriptor instead.
func (*InstrumentQuote) Descriptor() ([]byte, []int) {
	return file_orderbook_v1_orderbook_proto_rawDescGZIP(), []int{7}
}

func (x *InstrumentQuote) GetInstrument() string {
	if x != nil {
		return x.Instrument
	}
	return ""
}

func (x *InstrumentQuote) GetBestBidPrice() float64 {
	if x != nil {
		return x.BestBidPrice
	}
	return 0
}

func (x *InstrumentQuote) GetBestBidSize() float64 {
	if x != nil {
		return x.BestBidSize
	}
	return 0
}

func (x *InstrumentQuote) GetBestAskPrice() float64 {
	if x != nil {
		return x.BestAskPrice
	}
	return 0
}

func (x *InstrumentQuote) GetBestAskSize() float64 {
	if x != nil {
		return x.BestAskSize
	}
	return 0
}

type GetInstrumentQuoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instrument    string                 `protobuf:"bytes,1,opt,name=instrument,proto3" json:"instrument,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInstrumentQuoteRequest) Reset() {
	*x = GetInstrumentQuoteRequest{}
	mi := &file_orderbook_v1_orderbook_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInstrumentQuoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInstrumentQuoteRequest) ProtoMessage() {}

func (x *GetInstrumentQuoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orderbook_v1_orderbook_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInstrumentQuoteRequest.ProtoReflect.Descriptor instead.
func (*GetInstrumentQuoteRequest) Descriptor() ([]byte, []int) {
	return file_orderbook_v1_orderbook_proto_rawDescGZIP(), []int{8}
}

func (x *GetInstrumentQuoteRequest) GetInstrument() string {
	if x != nil {
		return x.Instrument
	}
	return ""
}

var File_orderbook_v1_orderbook_proto protoreflect.FileDescriptor

const file_orderbook_v1_orderbook_proto_rawDesc = "" +
	"\n" +
	"\x1corderbook/v1/orderbook.proto\x12\forderbook.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd7\x02\n" +
	"\x05Order\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12&\n" +
	"\x0fclient_order_id\x18\x02 \x01(\tR\rclientOrderId\x12\x1e\n" +
	"\n" +
	"instrument\x18\x03 \x01(\tR\n" +
	"instrument\x12&\n" +
	"\x04side\x18\x04 \x01(\x0e2\x12.orderbook.v1.SideR\x04side\x12+\n" +
	"\x04type\x18\x05 \x01(\x0e2\x17.orderbook.v1.OrderTypeR\x04type\x121\n" +
	"\x06status\x18\x06 \x01(\x0e2\x19.orderbook.v1.OrderStatusR\x06status\x12\x14\n" +
	"\x05price\x18\a \x01(\x01R\x05price\x12\x12\n" +
	"\x04size\x18\b \x01(\x01R\x04size\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xdb\x01\n" +
	"\x12CreateOrderRequest\x12&\n" +
	"\x0fclient_order_id\x18\x01 \x01(\tR\rclientOrderId\x12\x1e\n" +
	"\n" +
	"instrument\x18\x02 \x01(\tR\n" +
	"instrument\x12&\n" +
	"\x04side\x18\x03 \x01(\x0e2\x12.orderbook.v1.SideR\x04side\x12+\n" +
	"\x04type\x18\x04 \x01(\x0e2\x17.orderbook.v1.OrderTypeR\x04type\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x01R\x05price\x12\x12\n" +
	"\x04size\x18\x06 \x01(\x01R\x04size\",\n" +
	"\x0fGetOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\"/\n" +
	"\x12CancelOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\"c\n" +
	"\x13CancelOrderResponse\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x121\n" +
	"\x06status\x18\x02 \x01(\x0e2\x19.orderbook.v1.OrderStatusR\x06status\"3\n" +
	"\x11ListOrdersRequest\x12\x1e\n" +
	"\n" +
	"instrument\x18\x01 \x01(\tR\n" +
	"instrument\"A\n" +
	"\x12ListOrdersResponse\x12+\n" +
	"\x06orders\x18\x01 \x03(\v2\x13.orderbook.v1.OrderR\x06orders\"\xc5\x01\n" +
	"\x0fInstrumentQuote\x12\x1e\n" +
	"\n" +
	"instrument\x18\x01 \x01(\tR\n" +
	"instrument\x12$\n" +
	"\x0ebest_bid_price\x18\x02 \x01(\x01R\fbestBidPrice\x12\"\n" +
	"\rbest_bid_size\x18\x03 \x01(\x01R\vbestBidSize\x12$\n" +
	"\x0ebest_ask_price\x18\x04 \x01(\x01R\fbestAskPrice\x12\"\n" +
	"\rbest_ask_size\x18\x05 \x01(\x01R\vbestAskSize\";\n" +
	"\x19GetInstrumentQuoteRequest\x12\x1e\n" +
	"\n" +
	"instrument\x18\x01 \x01(\tR\n" +
	"instrument*/\n" +
	"\x04Side\x12\x14\n" +
	"\x10SIDE_UNSPECIFIED\x10\x00\x12\a\n" +
	"\x03BUY\x10\x01\x12\b\n" +
	"\x04SELL\x10\x02*s\n" +
	"\tOrderType\x12\x1a\n" +
	"\x16ORDER_TYPE_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05LIMIT\x10\x01\x12\n" +
	"\n" +
	"\x06MARKET\x10\x02\x12\x0e\n" +
	"\n" +
	"STOP_LIMIT\x10\x03\x12\b\n" +
	"\x04STOP\x10\x04\x12\x19\n" +
	"\x15TAKE_PROFIT_STOP_LOSS\x10\x05*B\n" +
	"\vOrderStatus\x12\x1c\n" +
	"\x18ORDER_STATUS_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aWORKING\x10\x01\x12\b\n" +
	"\x04DONE\x10\x022\xaa\x04\n" +
	"\tOrderBook\x12[\n" +
	"\vCreateOrder\x12 .orderbook.v1.CreateOrderRequest\x1a\x13.orderbook.v1.Order\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/v1/orders\x12]\n" +
	"\bGetOrder\x12\x1d.orderbook.v1.GetOrderRequest\x1a\x13.orderbook.v1.Order\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/v1/orders/{order_id}\x12q\n" +
	"\vCancelOrder\x12 .orderbook.v1.CancelOrderRequest\x1a!.orderbook.v1.CancelOrderResponse\"\x1d\x82\xd3\xe4\x93\x02\x17*\x15/v1/orders/{order_id}\x12c\n" +
	"\n" +
	"ListOrders\x12\x1f.orderbook.v1.ListOrdersRequest\x1a .orderbook.v1.ListOrdersResponse\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/v1/orders\x12\x88\x01\n" +
	"\x12GetInstrumentQuote\x12'.orderbook.v1.GetInstrumentQuoteRequest\x1a\x1d.orderbook.v1.InstrumentQuote\"*\x82\xd3\xe4\x93\x02$\x12\"/v1/instruments/{instrument}/quoteB<Z:github.com/kolobublik/limit-order-book/api/orderbook/v1;v1b\x06proto3"

var (
	file_orderbook_v1_orderbook_proto_rawDescOnce sync.Once
	file_orderbook_v1_orderbook_proto_rawDescData []byte
)

func file_orderbook_v1_orderbook_proto_rawDescGZIP() []byte {
	file_orderbook_v1_orderbook_proto_rawDescOnce.Do(func() {
		file_orderbook_v1_orderbook_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_orderbook_v1_orderbook_proto_rawDesc), len(file_orderbook_v1_orderbook_proto_rawDesc)))
	})
	return file_orderbook_v1_orderbook_proto_rawDescData
}

var file_orderbook_v1_orderbook_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_orderbook_v1_orderbook_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_orderbook_v1_orderbook_proto_goTypes = []any{
	(Side)(0),                         // 0: orderbook.v1.Side
	(OrderType)(0),                    // 1: orderbook.v1.OrderType
	(OrderStatus)(0),                  // 2: orderbook.v1.OrderStatus
	(*Order)(nil),                     // 3: orderbook.v1.Order
	(*CreateOrderRequest)(nil),        // 4: orderbook.v1.CreateOrderRequest
	(*GetOrderRequest)(nil),           // 5: orderbook.v1.GetOrderRequest
	(*CancelOrderRequest)(nil),        // 6: orderbook.v1.CancelOrderRequest
	(*CancelOrderResponse)(nil),       // 7: orderbook.v1.CancelOrderResponse
	(*ListOrdersRequest)(nil),         // 8: orderbook.v1.ListOrdersRequest
	(*ListOrdersResponse)(nil),        // 9: orderbook.v1.ListOrdersResponse
	(*InstrumentQuote)(nil),           // 10: orderbook.v1.InstrumentQuote
	(*GetInstrumentQuoteRequest)(nil), // 11: orderbook.v1.GetInstrumentQuoteRequest
	(*timestamppb.Timestamp)(nil),     // 12: google.protobuf.Timestamp
}
var file_orderbook_v1_orderbook_proto_depIdxs = []int32{
	0,  // 0: orderbook.v1.Order.side:type_name -> orderbook.v1.Side
	1,  // 1: orderbook.v1.Order.type:type_name -> orderbook.v1.OrderType
	2,  // 2: orderbook.v1.Order.status:type_name -> orderbook.v1.OrderStatus
	12, // 3: orderbook.v1.Order.created_at:type_name -> google.protobuf.Timestamp
	0,  // 4: orderbook.v1.CreateOrderRequest.side:type_name -> orderbook.v1.Side
	1,  // 5: orderbook.v1.CreateOrderRequest.type:type_name -> orderbook.v1.OrderType
	2,  // 6: orderbook.v1.CancelOrderResponse.status:type_name -> orderbook.v1.OrderStatus
	3,  // 7: orderbook.v1.ListOrdersResponse.orders:type_name -> orderbook.v1.Order
	4,  // 8: orderbook.v1.OrderBook.CreateOrder:input_type -> orderbook.v1.CreateOrderRequest
	5,  // 9: orderbook.v1.OrderBook.GetOrder:input_type -> orderbook.v1.GetOrderRequest
	6,  // 10: orderbook.v1.OrderBook.CancelOrder:input_type -> orderbook.v1.CancelOrderRequest
	8,  // 11: orderbook.v1.OrderBook.ListOrders:input_type -> orderbook.v1.ListOrdersRequest
	11, // 12: orderbook.v1.OrderBook.GetInstrumentQuote:input_type -> orderbook.v1.GetInstrumentQuoteRequest
	3,  // 13: orderbook.v1.OrderBook.CreateOrder:output_type -> orderbook.v1.Order
	3,  // 14: orderbook.v1.OrderBook.GetOrder:output_type -> orderbook.v1.Order
	7,  // 15: orderbook.v1.OrderBook.CancelOrder:output_type -> orderbook.v1.CancelOrderResponse
	9,  // 16: orderbook.v1.OrderBook.ListOrders:output_type -> orderbook.v1.ListOrdersResponse
	10, // 17: orderbook.v1.OrderBook.GetInstrumentQuote:output_type -> orderbook.v1.InstrumentQuote
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_orderbook_v1_orderbook_proto_init() }
func file_orderbook_v1_orderbook_proto_init() {
	if File_orderbook_v1_orderbook_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orderbook_v1_orderbook_proto_rawDesc), len(file_orderbook_v1_orderbook_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_orderbook_v1_orderbook_proto_goTypes,
		DependencyIndexes: file_orderbook_v1_orderbook_proto_depIdxs,
		EnumInfos:         file_orderbook_v1_orderbook_proto_enumTypes,
		MessageInfos:      file_orderbook_v1_orderbook_proto_msgTypes,
	}.Build()
	File_orderbook_v1_orderbook_proto = out.File
	file_orderbook_v1_orderbook_proto_goTypes = nil
	file_orderbook_v1_orderbook_proto_depIdxs = nil
}
